version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run: gradle assemble
      - run: gradle test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
  upload:
    docker:
      - image: circleci/openjdk:11.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a2:14:56:93:be:8e:a2:b2:fb:77:14:ed:a7:7a:42:5f"
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run: mkdir .signing
      - run: echo $SIGN_KEYSTORE | base64 -d > .signing/secring.gpg
      - run: gradle final publishNebulaPublicationToMavenRepository  -Prelease.useLastTag=true -PreleaseBuild=$RELEASE_BUILD -Psigning.secretKeyRingFile=.signing/secring.gpg -Psigning.keyId=$SIGN_KEY_ID -Psigning.password=$SIGN_PASSWORD -PuploadUsernameProp=$UPLOAD_USER -PuploadPasswordProp=$UPLOAD_PASSWORD
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_artifacts:
          path: build/libs
          destination: libs


workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
